### ISSUE TITLE
What command do you use to run the Flask project

### ISSUE THREAD

**Issue by tejaskj** [PrettyPrinted/youtube_video_code#73]
I am using the below command and it is throwing an error - 
`flask --app .\app.py --debug run`

The Error - 
` * Tip: There are .env or .flaskenv files present. Do "pip install python-dotenv" to use them.
Usage: flask run [OPTIONS]
Try 'flask run --help' for help.

Error: Failed to find Flask application or factory in module 'login_app_demo.app'. Use 'login_app_demo.app:name' to specify one.`

**Comment by bharathjinka09** [comment]
Run **pip install python-dotenv** to install the package. After that to run the app use the command **flask run**

**Comment by tejaskj** [comment]
I got it working. I found decouple-python to work better that the above package
