### ISSUE TITLE
Permissions / Security

### ISSUE THREAD

**Issue by jbarber877** [PrettyPrinted/youtube_video_code#74]
Hey, just wanted to let you know that there's an option to 'Delete Directory' popping up on the 'Testing In Flask'. Probably shouldn't be there

**Comment by PrettyPrinted** [comment]
I'm not sure what you mean. Could you share a screenshot?

**Comment by jbarber877** [comment]
Like this

![Screenshot 2023-02-06 185032](https://user-images.githubusercontent.com/80484728/217112990-75cb6f8e-271b-491e-b093-287bbdb3c512.png)

**Comment by PrettyPrinted** [comment]
That's not an issue because you don't have permissions to change the repo. If you try to use it, Github will fork my repo for you first, and then delete the directories in your copy of the repo. You can do this for any repo on Github, not just mine.

Thanks for your concern though.
